-- Migration 021: workspace binding type (path vs id)
--
-- Generalizes mappings beyond filesystem folders. A binding's `workspace_root`
-- is now a routing KEY that is either:
--   * 'path' — a normalized absolute folder path (the original behaviour), or
--   * 'id'   — an arbitrary exact-match string (a client id, machine name, or
--              any label a headless/remote client sends in X-Mcpmux-Workspace).
-- Existing rows are folder paths, so they default to 'path' (backward
-- compatible). Path keys are normalized + case-folded before comparison;
-- id keys are matched verbatim.
ALTER TABLE workspace_bindings ADD COLUMN binding_type TEXT NOT NULL DEFAULT 'path';
